name: Deploy Static Web App

on:
 workflow_dispatch:

jobs:
  build_and_deploy_job:
    
    runs-on: ubuntu-latest    
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - uses: cschleiden/replace-tokens@v1
        name: Replace Config Settings
        with:
          tokenPrefix: '__'
          tokenSuffix: '__'
          files: '["public/config.json"]'
        env:
          APICENTERHOSTNAME: ${{ secrets.API_CENTER_HOSTNAME }}
          ClientID: ${{ secrets.CLIENT_ID }}
          TenantID: ${{ secrets.TENANT_ID }}
          
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist"
